### ISSUE TITLE
What does order mean and more

### ISSUE THREAD

**Issue by ShyAlon** [oshri/sideproject-client#7]
I went over the code and I have a couple of comments:

1. What does the _**order**_ property mean? Does that mean ordinal? Should we allow the user to edit the order? (I don't think so). I think items should be sorted alphabetically.
2. The common properties should be shared through a base interface (like the one in the server) so _**id**_, _**name**_ and _**description**_ should be defined in the parent interface.

**Comment by oshri** [comment]
Fix
